
/**
 * ______________________________________________________
 * This file is part of ko-ascension-launcher project.
 * 
 * @author       Mustafa Kemal Gılor <mustafagilor@gmail.com> (2015)
 * .
 * SPDX-License-Identifier:	MIT
 * ______________________________________________________
 */

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "Explorer.h"

/////////////////////////////////////////////////////////////////////////////
// CExplorer

IMPLEMENT_DYNCREATE(CExplorer, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer operations
